import './style.css';
import { csvFor, datesFor, iso, validateSchedule, type Schedule, type Step } from './schedule';

const REAL_KEY = 'stepdown:real:schedule';
const DEMO_KEY = 'demo:stepdown:schedule';
const SEALED_KEY = 'stepdown:real:sealed';
const slug = 'taper-calendar-card';
let demo = location.pathname === '/demo' || new URLSearchParams(location.search).get('demo') === '1';
let schedule: Schedule | null = null;
let locked = false;
let encryptionPassphrase: string | null = null;
let licensed = (() => { try { return Boolean(JSON.parse(localStorage.getItem(`sb_license_status:${slug}`) || '{}').valid); } catch { return false; } })();
let notice = '';

function sample(): Schedule { return { id: crypto.randomUUID(), medication: 'Example medication', clinicianText: 'Example only. Follow the clinician-provided instructions for your own medication. Take the stated dose with breakfast. Contact your clinician or pharmacist with questions.', createdAt: new Date().toISOString(), acknowledgements: {}, steps: [
  { id: crypto.randomUUID(), start: iso(new Date()), end: plus(4), dose: '20 mg once daily', instructions: 'Take with breakfast.' },
  { id: crypto.randomUUID(), start: plus(5), end: plus(9), dose: '10 mg once daily', instructions: 'Take with breakfast.' },
  { id: crypto.randomUUID(), start: plus(10), end: plus(13), dose: '5 mg once daily', instructions: 'Take with breakfast.' }
]}; }
function plus(n: number) { const d = new Date(); d.setDate(d.getDate() + n); return iso(d); }
function store() { return new Promise<IDBDatabase>((resolve, reject) => { const request=indexedDB.open('stepdown-card',1); request.onupgradeneeded=()=>request.result.createObjectStore('cards'); request.onsuccess=()=>resolve(request.result); request.onerror=()=>reject(request.error); }); }
async function readStored(key: string) { const db=await store(); return new Promise<string | undefined>((resolve,reject)=>{const r=db.transaction('cards').objectStore('cards').get(key); r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);}); }
async function writeStored(key: string, value: string) { const db=await store(); return new Promise<void>((resolve,reject)=>{const r=db.transaction('cards','readwrite').objectStore('cards').put(value,key);r.onsuccess=()=>resolve();r.onerror=()=>reject(r.error);}); }
async function removeStored(key: string) { const db=await store(); return new Promise<void>((resolve,reject)=>{const r=db.transaction('cards','readwrite').objectStore('cards').delete(key);r.onsuccess=()=>resolve();r.onerror=()=>reject(r.error);}); }
function save() { if (!schedule) return; if (demo) void writeStored(DEMO_KEY, JSON.stringify(schedule)); else if (encryptionPassphrase) void seal(schedule, encryptionPassphrase); else void writeStored(REAL_KEY, JSON.stringify(schedule)); }
function b64(bytes: Uint8Array) { return btoa(String.fromCharCode(...bytes)); }
function unb64(text: string) { return Uint8Array.from(atob(text), c => c.charCodeAt(0)); }
async function cryptKey(passphrase: string, salt: Uint8Array) { const base = await crypto.subtle.importKey('raw', new TextEncoder().encode(passphrase), 'PBKDF2', false, ['deriveKey']); return crypto.subtle.deriveKey({name:'PBKDF2',salt:salt.buffer as ArrayBuffer,iterations:150000,hash:'SHA-256'},base,{name:'AES-GCM',length:256},false,['encrypt','decrypt']); }
async function seal(value: Schedule, passphrase: string) { const salt=crypto.getRandomValues(new Uint8Array(16)); const iv=crypto.getRandomValues(new Uint8Array(12)); const key=await cryptKey(passphrase,salt); const encrypted=await crypto.subtle.encrypt({name:'AES-GCM',iv:iv.buffer as ArrayBuffer},key,new TextEncoder().encode(JSON.stringify(value))); await writeStored(SEALED_KEY,JSON.stringify({salt:b64(salt),iv:b64(iv),data:b64(new Uint8Array(encrypted))})); await removeStored(REAL_KEY); }
async function unseal(passphrase: string) { const item=await readStored(SEALED_KEY); if(!item) throw Error(); const p=JSON.parse(item); const key=await cryptKey(passphrase,unb64(p.salt)); const iv=unb64(p.iv); const data=unb64(p.data); const decrypted=await crypto.subtle.decrypt({name:'AES-GCM',iv:iv.buffer as ArrayBuffer},key,data.buffer as ArrayBuffer); return JSON.parse(new TextDecoder().decode(decrypted)) as Schedule; }
function esc(value: string) { return value.replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]!)); }
function app() {
  const route = location.pathname;
  document.title = route === '/privacy' ? 'Privacy — StepDown Card' : route === '/terms' ? 'Terms — StepDown Card' : demo ? 'Demo — StepDown Card' : 'StepDown Card — track a taper day by day';
  document.querySelector('#app')!.innerHTML = `${header()}<main id="main" tabindex="-1">${route === '/privacy' ? privacy() : route === '/terms' ? terms() : appScreen()}</main>${footer()}<div class="toast" aria-live="polite">${notice}</div>`;
  bind();
}
function header() { return `<header><a class="wordmark" href="/" data-route>Step<span>Down</span> Card</a><nav aria-label="Primary"><a href="/demo" data-route>Demo</a><a href="#schedule">Schedule</a><a href="/privacy" data-route>Privacy</a></nav></header>`; }
function footer() { return `<footer><p>A private card for a clinician-provided taper.</p><p><a href="/privacy" data-route>Privacy</a> · <a href="/terms" data-route>Terms</a> · Built by Param Factory · v1.0.0</p></footer>`; }
function landing() { return `<section class="landing" aria-labelledby="page-title"><div class="hero-copy"><p class="eyebrow">PRIVATE TAPER TRANSCRIPTION</p><h1 id="page-title">Track your taper day by day</h1><p class="lede">For people following clinician instructions who need each dose and checked day in one private card.</p><div class="actions"><button class="primary" id="try-demo">Try it with sample data</button><span>Loads an example card. Nothing is saved.</span><button class="quiet" id="start-real">Start your own card</button></div><ul class="facts"><li>Works after you first open it.</li><li>Stores your card on this device.</li><li>$9 one-time for extra print layouts.</li></ul></div><figure class="hero-art"><img src="/hero.webp" width="768" height="512" alt="An opened cassette case with blank cards and a small calendar, representing a finite written schedule." fetchpriority="high" /><figcaption>Keep the written plan visible.</figcaption></figure></section>
<section class="how" aria-labelledby="how-title"><h2 id="how-title">Make a card in three steps</h2><ol><li><b>Copy</b> the clinician’s instructions exactly.</li><li><b>Mark</b> each dose step and date.</li><li><b>Check</b> each day, then print or export.</li></ol></section>
<section class="limits" aria-labelledby="limits-title"><h2 id="limits-title">What this card does not do</h2><p>It does not calculate a taper, recommend a dose, check interactions, or replace your clinician. If instructions are unclear, contact your clinician or pharmacist.</p></section>`; }
function editor(s: Schedule | null) {
  const current = s || {medication:'', clinicianText:'', steps:[{id: crypto.randomUUID(), start:iso(new Date()), end:iso(new Date()), dose:'', instructions:''}]};
  return `<section class="editor" id="schedule" aria-labelledby="write-title"><p class="eyebrow">YOUR WRITTEN CARD</p><h2 id="write-title">Write your clinician’s taper</h2><p class="safety">Copy instructions exactly. StepDown Card cannot tell you what dose to take.</p><form id="schedule-form"><label>Medication or treatment name<input required name="medication" value="${esc(current.medication)}" autocomplete="off" /></label><label>Clinician instructions, copied exactly<textarea required name="clinicianText" rows="4">${esc(current.clinicianText)}</textarea></label><fieldset><legend>Dose steps</legend><div id="step-list">${current.steps.map(stepRow).join('')}</div><button class="quiet" type="button" id="add-step">Add a dose step</button></fieldset><div class="actions"><button class="primary" type="submit">Save this card</button><span>Your card stays on this device.</span></div></form></section>`;
}
function stepRow(step: Step) { return `<div class="step-row" data-id="${step.id}"><label>Start<input required type="date" name="start" value="${step.start}" /></label><label>End<input required type="date" name="end" value="${step.end}" /></label><label>Exact dose<input required name="dose" value="${esc(step.dose)}" placeholder="For example: 10 mg once daily" /></label><label>Step note<input name="instructions" value="${esc(step.instructions)}" placeholder="For example: take with food" /></label><button class="remove" type="button" aria-label="Remove this dose step">×</button></div>`; }
function card(s: Schedule) { const all = datesFor(s.steps); const completed = Object.keys(s.acknowledgements).length; return `<section class="card" id="schedule" aria-labelledby="page-title"><div class="card-head"><div><p class="eyebrow">${demo ? 'DEMO CARD' : 'SCHEDULE CARD'}</p><h1 id="page-title">${esc(s.medication)}</h1><p>${all.length} scheduled days · ${completed} checked</p></div><div class="toolbar"><button class="quiet" id="edit">Edit card</button><button class="quiet" id="export-csv">Export CSV</button><button class="quiet" id="export-json">Export backup</button><button class="primary" id="print">Print card</button></div></div><aside class="safety"><strong>Follow the clinician’s directions.</strong> This card records them. It does not change them.</aside><article class="instructions"><h2>Clinician instructions</h2><p>${esc(s.clinicianText).replaceAll('\n','<br>')}</p></article><section class="tracks" aria-labelledby="days-title"><h2 id="days-title">Daily checks</h2>${all.map(({date, step}, i) => dayRow(date, step, i)).join('')}</section><section class="ownership"><h2>Keep a copy you control</h2><p>Export a backup before changing devices. Acknowledgements include the local time you checked each day.</p><label class="import">Import backup<input id="import-json" type="file" accept="application/json" /></label>${!demo ? `<div class="encrypt"><h3>Encrypt this card on this device</h3><p>Set a passphrase to lock this card. Keep an exported backup. A forgotten passphrase cannot be recovered.</p><label>New passphrase<input id="encrypt-pass" type="password" autocomplete="new-password" /></label><button class="quiet" id="encrypt">Encrypt this card</button></div>` : ''}</section></section>`; }
function dayRow(date: string, step: Step, index: number) { const done = schedule!.acknowledgements[date]; const today = date === iso(new Date()); return `<div class="day ${done ? 'done' : ''} ${today ? 'today' : ''}"><span class="track">${String(index + 1).padStart(2,'0')}</span><time datetime="${date}">${new Date(`${date}T12:00:00`).toLocaleDateString(undefined,{weekday:'short',month:'short',day:'numeric'})}</time><div><b>${esc(step.dose)}</b>${step.instructions ? `<small>${esc(step.instructions)}</small>` : ''}</div><button class="check" data-date="${date}" aria-pressed="${!!done}">${done ? 'Checked' : 'Check this day'}</button></div>`; }
function paid() { return `<section class="paid" aria-labelledby="paid-title"><h2 id="paid-title">Optional paper pack — $9 once</h2><p>${licensed ? 'Paper pack is active on this device. Print the compact card when you need a smaller handoff.' : 'Adds a compact print card. Core cards and exports stay free.'}</p>${licensed ? '<button class="primary" id="print-compact">Print compact card</button>' : `<a class="buy" href="https://api.sociobot.in/api/v1/products/${slug}/checkout">Buy the paper pack</a><label>Have a license? Paste it<input id="license" autocomplete="off" /></label><button class="quiet" id="restore">Restore purchase</button>`}</section>`; }
function lockedScreen() { return `<section class="editor"><p class="eyebrow">ENCRYPTED CARD</p><h1 id="page-title">Open your encrypted card</h1><p>Your schedule is encrypted in this browser. Enter the passphrase you set on this device.</p><label>Passphrase<input id="unlock-pass" type="password" autocomplete="current-password" /></label><div class="actions"><button class="primary" id="unlock">Open this card</button></div><p class="safety">A forgotten passphrase cannot be recovered. Restore an exported backup instead.</p></section>`; }
function appScreen() { if (locked) return lockedScreen(); return `${demo ? `<div class="demo"><b>Demo — sample data, nothing is saved</b><button id="reset-demo">Reset demo</button><button id="leave-demo">Start for real</button></div>` : ''}${schedule ? card(schedule) : landing()}${!schedule && !demo ? editor(null) : ''}${schedule ? paid() : ''}`; }
function privacy() { return `<article class="legal"><h1>Privacy for StepDown Card</h1><p>Schedule data stays in this browser unless you export it. The app has no account and no analytics.</p><h2>Data on this device</h2><p>Your card, dose steps, and acknowledgements use browser storage. Clear site data or use a private browser session to remove them.</p><h2>Purchase data</h2><p>If you choose the optional paper pack, the merchant receives what checkout requires. A license token is stored in this browser so the app can restore your purchase.</p></article>`; }
function terms() { return `<article class="legal"><h1>Terms for StepDown Card</h1><p>StepDown Card is a personal transcription tool. It is not medical advice or a medical device.</p><h2>Use the clinician’s directions</h2><p>Do not use this app to calculate, change, or choose a taper. Ask your clinician or pharmacist when directions are unclear.</p><h2>Optional purchase</h2><p>The paper pack is a $9 one-time license. Sociobot and Dodo handle payment and refunds.</p></article>`; }
function download(name: string, type: string, body: string) { const a = document.createElement('a'); a.href = URL.createObjectURL(new Blob([body], {type})); a.download=name; a.click(); URL.revokeObjectURL(a.href); }
function bind() {
  document.querySelectorAll<HTMLAnchorElement>('[data-route]').forEach(a => a.onclick = e => { e.preventDefault(); history.pushState({},'',a.href); app(); document.querySelector<HTMLElement>('h1')?.focus(); });
  document.querySelector('#try-demo')?.addEventListener('click', () => { demo=true; history.pushState({},'', '/demo'); schedule=sample(); save(); app(); });
  document.querySelector('#start-real')?.addEventListener('click', () => { demo=false; history.pushState({},'', '/'); schedule=null; app(); });
  document.querySelector('#reset-demo')?.addEventListener('click', () => { schedule=sample(); save(); notice='The example card was reset.'; app(); });
  document.querySelector('#leave-demo')?.addEventListener('click', () => { void removeStored(DEMO_KEY); demo=false; schedule=null; history.pushState({},'', '/'); app(); });
  document.querySelector('#unlock')?.addEventListener('click',async()=>{try { schedule=await unseal((document.querySelector('#unlock-pass') as HTMLInputElement).value); encryptionPassphrase=(document.querySelector('#unlock-pass') as HTMLInputElement).value; locked=false; notice='Your encrypted card is open for this session.'; app(); } catch {notice='That passphrase did not open this card. Try again or restore a backup.'; app();}});
  document.querySelector('#add-step')?.addEventListener('click', () => document.querySelector('#step-list')?.insertAdjacentHTML('beforeend', stepRow({id:crypto.randomUUID(),start:iso(new Date()),end:iso(new Date()),dose:'',instructions:''})));
  document.querySelector('#step-list')?.addEventListener('click', e => { if ((e.target as HTMLElement).classList.contains('remove')) (e.target as HTMLElement).closest('.step-row')?.remove(); });
  document.querySelector<HTMLFormElement>('#schedule-form')?.addEventListener('submit', e => { e.preventDefault(); const f = new FormData(e.currentTarget as HTMLFormElement); const rows=[...document.querySelectorAll<HTMLElement>('.step-row')]; const steps=rows.map(row=>({id:row.dataset.id!,start:(row.querySelector('[name=start]') as HTMLInputElement).value,end:(row.querySelector('[name=end]') as HTMLInputElement).value,dose:(row.querySelector('[name=dose]') as HTMLInputElement).value,instructions:(row.querySelector('[name=instructions]') as HTMLInputElement).value})); const error=validateSchedule(String(f.get('medication')),String(f.get('clinicianText')),steps); if(error){notice=error; app(); return;} schedule={id:crypto.randomUUID(),medication:String(f.get('medication')),clinicianText:String(f.get('clinicianText')),steps,createdAt:new Date().toISOString(),acknowledgements:{}}; save(); notice='Your card is saved on this device.'; app(); });
  document.querySelector('#edit')?.addEventListener('click', () => { const copy=schedule!; document.querySelector('#schedule')!.outerHTML=editor(copy); bind(); });
  document.querySelectorAll<HTMLButtonElement>('.check').forEach(btn=>btn.onclick=()=>{ const d=btn.dataset.date!; if(schedule!.acknowledgements[d]) delete schedule!.acknowledgements[d]; else schedule!.acknowledgements[d]=new Date().toLocaleString(); save(); app(); });
  document.querySelector('#export-csv')?.addEventListener('click',()=> download('stepdown-log.csv','text/csv',csvFor(schedule!)));
  document.querySelector('#export-json')?.addEventListener('click',()=> download('stepdown-backup.json','application/json',JSON.stringify(schedule,null,2)));
  document.querySelector('#print')?.addEventListener('click',()=>window.print());
  document.querySelector('#print-compact')?.addEventListener('click',()=>{document.body.classList.add('compact-print');window.print();document.body.classList.remove('compact-print');});
  document.querySelector('#encrypt')?.addEventListener('click',async()=>{const pass=(document.querySelector('#encrypt-pass') as HTMLInputElement).value; if(pass.length<8){notice='Use at least 8 characters for the passphrase.';app();return;} encryptionPassphrase=pass; await seal(schedule!,pass); notice='This card is encrypted. Keep your exported backup and passphrase safe.'; app();});
  document.querySelector<HTMLInputElement>('#import-json')?.addEventListener('change',async e=>{const file=(e.currentTarget as HTMLInputElement).files?.[0]; if(!file)return; try {const next=JSON.parse(await file.text()) as Schedule; if(!validateSchedule(next.medication,next.clinicianText,next.steps)){schedule=next;save();notice='Backup imported.';app();} else throw Error();} catch {notice='That backup could not be read. Choose a StepDown Card backup file.';app();}});
  document.querySelector('#restore')?.addEventListener('click',async()=>{const token=(document.querySelector('#license') as HTMLInputElement)?.value.trim(); if(!token)return; localStorage.setItem(`sb_license:${slug}`,token); notice='License saved. It will be checked when you are online.'; app(); verifyLicense(token);});
}
async function verifyLicense(token: string) { try { const cached=JSON.parse(localStorage.getItem(`sb_license_status:${slug}`) || '{}'); if(cached.at && Date.now()-cached.at<86400000) return; const r=await fetch(`https://api.sociobot.in/api/v1/products/${slug}/verify?license=${encodeURIComponent(token)}`); const data=await r.json(); licensed=Boolean(data.valid); localStorage.setItem(`sb_license_status:${slug}`,JSON.stringify({at:Date.now(),valid:licensed})); app(); } catch { /* Offline keeps a cached paper pack state and always keeps the free card usable. */ } }
window.addEventListener('popstate', app);
if ('serviceWorker' in navigator) navigator.serviceWorker.register('/sw.js').catch(()=>{});
const license = new URLSearchParams(location.search).get('license'); if (license) { localStorage.setItem(`sb_license:${slug}`, license); history.replaceState({},'',location.pathname); verifyLicense(license); }
const savedLicense=localStorage.getItem(`sb_license:${slug}`); if (savedLicense) verifyLicense(savedLicense);
async function hydrate() { try { const sealed=await readStored(SEALED_KEY); locked=!demo && !!sealed; const saved=await readStored(demo ? DEMO_KEY : REAL_KEY); schedule=saved ? JSON.parse(saved) as Schedule : null; if(demo && !schedule){schedule=sample();save();} } catch { notice='This browser could not open local storage. Try a standard browser window.'; } app(); }
hydrate();
